### ISSUE TITLE
No module and object

### ISSUE THREAD

**Issue by Eychics** [ShotgunNinja/Kerbalism#103]
(Sorry for my english i'm french)

Hello, I have no object coming from Kerbalism

I only have the simulation system: 
![image](https://cloud.githubusercontent.com/assets/7293238/25041421/34bb41dc-2110-11e7-8d18-b4b149a2f95c.png)

The Gravity ring is not present for example while it is in my GameData
![image](https://cloud.githubusercontent.com/assets/7293238/25041405/0f27b4e6-2110-11e7-8fa1-56574422a6e1.png)
![image](https://cloud.githubusercontent.com/assets/7293238/25041440/4fca5e54-2110-11e7-9943-3ec949bd565d.png)

Big thanks.

**Comment by ShotgunNinja** [comment]
Make sure to have [ModuleManager ](http://forum.kerbalspaceprogram.com/index.php?/topic/50533-121-module-manager-275-november-29th-2016-better-late-than-never/) installed.

**Comment by Eychics** [comment]
It is already installed

![image](https://cloud.githubusercontent.com/assets/7293238/25047250/efd13970-2135-11e7-8800-c45e07e127e8.png)

**Comment by ShotgunNinja** [comment]
You are using an old version of ModuleManager. Update it to the last version, **2.7.5**

**Comment by Eychics** [comment]
Its work big thanks ! :D
