### ISSUE TITLE
An active Science Lab doesn't consume energy in background

### ISSUE THREAD

**Issue by OzoneGrif** [ShotgunNinja/Kerbalism#11]
Kerbalism simulates vessel's energy consumption in background and it seems to work with antennas, but I noticed it doesn't work with an active science lab : it calculates as if the lab was disabled.

When the mod shots a warning and turns off unessential systems, it should turn off the science lab as well (if it doesn't already).

PS: I would totally love the Climate Control system to make use of radiators (these babies are useless otherwise)

**Comment by ShotgunNinja** [comment]
The lab isn't simulated in background currently, but it may be possible in a future version.

**Comment by ShotgunNinja** [comment]
Postponed to 0.9.9.6

**Comment by ShotgunNinja** [comment]
This didn't make it for 0.9.9.6, delayed to the next one.

**Comment by ShotgunNinja** [comment]
At last, this has been implemented in next version.
