### ISSUE TITLE
Greenhouse ready to harvest

### ISSUE THREAD

**Issue by chrissnave** [ShotgunNinja/Kerbalism#115]
I'm not sure if this is an issue or if I'm just I'm missing something here but how do I harvest the food from my greenhouse?

Its been 200 days & I received a message saying the crop is "ready to harvest". I have storage aboard for the food but I see no option to actually harvest anything? I even tried docking a supply ship with additional food storage. That didn't help either.

KSP 1.2.2.1622
Kerbilism 1.2.5 - default profile

![screenshot139 copy](https://cloud.githubusercontent.com/assets/12790092/25351095/8557e5ae-28f5-11e7-847a-dca1fb61133e.jpg)

**Comment by PiezPiedPy** [comment]
Not sure but maybe you can't harvest because there are no kerbal's on board

**Comment by chrissnave** [comment]
Hmm okay I'll try sending up manned supply ship, dock that with the greenhouse & see if that helps. Will report back results...

**Comment by chrissnave** [comment]
Okay apparently Kerbals are required in order to harvest a greenhouse. I flew up a few Kerbals, docked with my automated greenhouse ship & now I see a harvest button. Awesome! Okay so I can grow food without Kerbals aboard but need them to do the actual harvesting. I can work with that. Thanks a bunch PiezPiedPy for the suggestion & a big thank you to ShotgunNinja for such a great MOD.

![screenshot141 copy](https://cloud.githubusercontent.com/assets/12790092/25360754/80075a08-2918-11e7-82a7-41cd4f929a84.jpg)
