### ISSUE TITLE
Gravity Ring not adding to comfort 

### ISSUE THREAD

**Issue by 057Kingpin** [ShotgunNinja/Kerbalism#119]
Enabling the gravity ring marks the "firm-ground" as yes, however it doesn't seem to change the level of comfort. I noticed the comfort level was never reaching over moderate even with all comforts added. After looking into the setting and experimenting with different values I found the gravity ring does not change the level of comfort. Adding and deploying the gravity ring on the mk 1 pod does nothing to the comfort level, it remains at none while all other parts that change comfort and affect comfort flags  will affect the comfort level (adjusting their settings will also change how much comfort each flag adds).

I tried looking into the gravity ring config file and other config files but was unable to find any place where firm-ground was actually associated with the gravity ring despite it being able to change the flag.

**Comment by ShotgunNinja** [comment]
Thank you for the report. This has been fixed [here](https://github.com/ShotgunNinja/Kerbalism/commit/602f5c260fc6f1805d4f8778306791a27a79d199), and will be include in next release.
