### ISSUE TITLE
Expand Compatibility for Bluedog Design Bureau parts

### ISSUE THREAD

**Issue by dieDoktor** [ShotgunNinja/Kerbalism#121]
Currently the config files that add compatibility for Bluedog Design Bureau (BDB) cover only parts that are marked as antennas, and only function as such. However, BDB has antennas embedded in probe bodies which are not registered by Kerbalism, and as a result are not able to be used solely on their own, as is intended.

**Comment by dieDoktor** [comment]
I get that maybe communicability issues are not something that are intended to be supported. I only open the issue because Bluedog.cfg already exists in the Kerbalism repo and has some items covered.

**Comment by ShotgunNinja** [comment]
The [support patch](https://github.com/ShotgunNinja/Kerbalism/blob/master/GameData/Kerbalism/Support/Bluedog.cfg) was improved in last update (**1.2.6**), and now support:
- standalone antennas
- embedded antennas in probe cores
- laboratory and geiger counter experiment.
- custom habitat volume/surfaces

Through I'm not sure the antenna/probe coverage is 100%. Could you point me to what parts are not covered?

**Comment by dieDoktor** [comment]
I have really bad timing. I'm just going to go dig a hole and die now. Missed the new release between deciding to open this issue and actually doing it.

**Comment by ShotgunNinja** [comment]
Ah! No worries :-)
