### ISSUE TITLE
Repeated Kerbalism exception when playing Scenarios 

### ISSUE THREAD

**Issue by jessegoodell** [ShotgunNinja/Kerbalism#124]
With Kerbalism installed, scenario based games experience broken context menus and poor performance.  KSP log (attached) reveals a repeated exception in KERBALISM.Reliability.Update()

[KSP.log.txt](https://github.com/ShotgunNinja/Kerbalism/files/980391/KSP.log.txt)

**Comment by ShotgunNinja** [comment]
Thanks for the report, this has been fixed [here](https://github.com/ShotgunNinja/Kerbalism/commit/c2e43ce4a971b1730f7c04ef967dc8c92441e85e).
