### ISSUE TITLE
Drill-O-Matic Mining Excavator not working

### ISSUE THREAD

**Issue by henrythasler** [ShotgunNinja/Kerbalism#127]
**Expected behavior:** Ore extraction with Drill-O-Matic Mining Excavator can be initiated independent of vessel configuration.  
**Observed behavior:** Enabling of ore extraction depends on (seemingly random) part placement. See screenshots 
![screenshot1](https://cloud.githubusercontent.com/assets/6277203/25779086/747139aa-3310-11e7-9337-018de36b7c46.png)
![screenshot2](https://cloud.githubusercontent.com/assets/6277203/25779098/77c78ca8-3310-11e7-94b4-82fc98ba63db.png)

After removing the small holding tank, ore extraction can't be started although the radial tank is still present. 

**Tested with:**
* KSP 1.2.2.1622
* Kerbalism: 1.2.7
* Module Manager: 2.7.6
no other mods where installed

**Comment by ShotgunNinja** [comment]
Thanks for the detailed report. There is probably an error in how the position of the drill head or the terrain height are calculated.

**Comment by ShotgunNinja** [comment]
Fixed [here](https://github.com/ShotgunNinja/Kerbalism/commit/3b1b48a411a90c72eb955c03b894b3dc43158a7c).

Note that now the terrain is detected properly, and this mean that drills will not reach the ground from the upgraded launch platform (or from the 'grass-like' platform around some buildings).
