### ISSUE TITLE
food weight

### ISSUE THREAD

**Issue by HalcyonCorpse15** [ShotgunNinja/Kerbalism#15]
sorry for my language, I use the translator.
food weight for day = 50kg? It is not too much ? rocket`s too heavy. =(
real diet weighs about 2kg

**Comment by lordcirth** [comment]
Don't forget that the Food resource would include water, which is minimum 2 Liters per day, which is 2 kg.  But 50kg is still too much, I think.

**Comment by ShotgunNinja** [comment]
I'm doing some tests with 10kg food and 4kg oxygen per-day. Keep in mind food represent all consumables, and oxygen the life support proper. I'll have to investigate if changing mass break old savegames.

**Comment by ShotgunNinja** [comment]
I'm doing some tests with 10kg food and 4kg oxygen per-day. Keep in mind food represent all consumables, and oxygen the life support proper. I'll have to investigate if changing mass break old savegames.

**Comment by HalcyonCorpse15** [comment]
can be renamed resource "food" in the "supply"? 10kg a day is normal. in general, your mod simply wonderful. Thank you.

**Comment by lordcirth** [comment]
"Supplies" is already used by USI-LS.  And it's less clear.

**Comment by HalcyonCorpse15** [comment]
let it be food. it is not so important.=)

**Comment by OzoneGrif** [comment]
Food is great, but I agree the weight of food is very harsh for long trips. Also I like the idea to have food stored in the habitable parts, but some parts should offer a bigger storage than others (the hitchiker part for example which has tons of room inside).

The food tanks should be reserved for very long trips (many month), space stations or bases.

A simple trip to Minmus shouldn't require food tanks.

**Comment by HalcyonCorpse15** [comment]
fly to minimus 15-25 days. not sure what MK1 command pod is designed to store large amounts of food, oxygen, water, kerbonaut. =)

**Comment by OzoneGrif** [comment]
Sure, I agree with you Halcyon, but my comment was mostly on a gameplay basis, not realism (although that can probably be worked out with nice tweaking) :)

**Comment by ShotgunNinja** [comment]
Changed for version 0.9.9.5.
