### ISSUE TITLE
What is the huge field around the sun?

### ISSUE THREAD

**Issue by Kataklysmos** [ShotgunNinja/Kerbalism#159]
I just installed the mod, so it's entirely possible that I just have no idea what I'm talking about and that it's intended to work this way, it just seems sort of odd.

I was looking at the radiation fields for each body, and I noticed that when the Sun or Eeloo are selected, and the magnetopause option is set to show, a massive field is shown around the entire solar system. Is this correct? It seems to me that it must be a bug that Eeloo shows this as well as the Sun.

**Comment by ShotgunNinja** [comment]
That is the heliosphere, and its border is the heliopause.

When you select a body, I show you the first field in the hierarchy that influence the point in space where the celestial body is at the moment. Therefore, if you select Eeloo, and having Eeloo no field of its own, the first one in the hierarchy is the one associated with the sun.

The heliosphere field protect the whole system from most of the extra-solar plasma radiation. The portion that manage to reach the interior of the system is what we call 'cosmic radiation'. Outside, radiation levels are much higher.

There is a contract to reward the users that dare to cross the heliopause, into interstellar space.

Have fun.
