### ISSUE TITLE
Kerbalism breaks remote tech

### ISSUE THREAD

**Issue by Goury** [ShotgunNinja/Kerbalism#17]
All but com16 and 88-88 antennas is broken for direct control of probes for remote tech if kerbalism is present.

**Comment by ShotgunNinja** [comment]
Both mods don't work together as of now. Wait until 0.9.9.5 is released and then you will be able to use RemoteTech together with this mod.

**Comment by Goury** [comment]
So bug is present and known.
Why do you close it then?
Do you want to hide the truth?

**Comment by lordcirth** [comment]
It's not a bug - it's a fact.  Why would it be surprising that 2 mods that take over antennas and provide the same functionality don't work together?  I actually think it's surprising that he's taking the time to make them compatible instead of slapping a warning on it, like I would do.

**Comment by Goury** [comment]
It is an issue and it is present

**Comment by ShotgunNinja** [comment]
I do updates on my own local copy and only push releases proper in here. This issue was closed because 0.9.9.5 disable its own signal mechanic when RemoteTech is detected. Note that 0.9.9.5 is not released yet. Please don't be so dramatic
