### ISSUE TITLE
Desactivate message by default and pause when there is one

### ISSUE THREAD

**Issue by SylvainLasnier** [ShotgunNinja/Kerbalism#174]
Hi,
Due to Kerbalism rules, most of vessel are unmanned probe, IMHO. And message dont matter a lot for them.
In another hand tracking messages are vital for manned station. And it is easy to miss some critical message when your are wrapping to the next maneuver.

So, is it possible to desactivate message by default? 
![image](https://user-images.githubusercontent.com/469796/44837373-c7343180-ac39-11e8-823b-7a92ca6cd719.png)

Is it possible to pause the game when a message is display?

Is it possible switch to the vessel by clicking on this list?
![image](https://user-images.githubusercontent.com/469796/44837701-9b657b80-ac3a-11e8-98c5-b43106788f1b.png)

Thanks :)

**Comment by MartinDomig** [comment]
Hi

This project is a bit outdated, currently the development happens in this fork:   [github.com/steamp0rt/Kerbalism](https://github.com/steamp0rt/Kerbalism)

Please post your issues there.

**Comment by SylvainLasnier** [comment]
Thanks for the information
