### ISSUE TITLE
Community Tech Tree compatibility?

### ISSUE THREAD

**Issue by seanmckdev** [ShotgunNinja/Kerbalism#176]
Engineering Tech Tree hasn't been updated in ages, but Community Tech Tree is still active. Adding support for career mode would be amazing.

**Comment by lordcirth** [comment]
Kerbalism is now developed over at: https://github.com/Kerbalism/Kerbalism/
I have made some patches for CTT, but if you have more suggestions, open an issue there and tag me. Thanks!
