### ISSUE TITLE
Feature-Hooks.cs idea

### ISSUE THREAD

**Issue by Wardstone111** [ShotgunNinja/Kerbalism#18]
You could add a module that disables food and oxygen so that other life support mods are compatable.

**Comment by ShotgunNinja** [comment]
I'm releasing a new version this weekend, 0.9.9.5, that is essentially a big refactor of Kerbalism into an engine that run arbitrary life-support rules. Without the food/oxygen rules, it can effectively be run together with another arbitrary life-support mod.

Maybe unrelated to your question, there is also a Hook to disable all mechanics (including life-support ones) for a specific Kerbal: _DisableKerbal()_ - its used by mods such as DeepFreeze to suspend life-support and other mechanics for frozen kerbals for example.
