### ISSUE TITLE
Kerbals "duplicate" after re-boarding a Vessel

### ISSUE THREAD

**Issue by TripleKiller666** [ShotgunNinja/Kerbalism#19]
https://github.com/KospY/KIS/issues/136

Creator of KIS suggested it could be an incompatibility with this mod, any chance to still get them to work together if thats the case?

**Comment by ShotgunNinja** [comment]
0.9.9.4 was setting the helmet state on top of the KIS one. 0.9.9.5 instead detect KIS and use the helmet state as set by KIS. Other than this, there is nothing in Kerbalism code _apparently_ that can trigger the behavior you are seeing. Can you confirm this is still happening in 0.9.9.5? Are you able to reproduce the issue with only KIS and Kerbalism installed (and their dependencies)?

**Comment by ShotgunNinja** [comment]
Closed, not a Kerbalism issue as per [KospY/KIS#136](https://github.com/KospY/KIS/issues/136)
