### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by hraban35** [ShotgunNinja/Kerbalism#2]
Missing a forum for discussion and contribution elementary elements such as water and waste in the Mod.

**Comment by ShotgunNinja** [comment]
There is the [thread](http://forum.kerbalspaceprogram.com/index.php?/topic/137227-kerbalism/) on KSPforums (I'm assuming you weren't aware of it when you raised this?). We can also discuss here. 

Waste is already in the mod, only the user is not supposed to see it (its a pseudo-resource). Every time a Kerbal consume food it also produce waste. Then the waste is used by the Greenhouses in the same vessel, if any, that obtain a bonus on growth from consuming it.

Water I'll really like to add, but it must have something unique about it gameplay-wise. If you have some ideas please share them here or on the forum.
