### ISSUE TITLE
Dual axis solar panels from Dr. Jet's Chop Shop not generate power in background

### ISSUE THREAD

**Issue by thghca** [ShotgunNinja/Kerbalism#21]
My sats with SSP panels charging only when active.

**Comment by ShotgunNinja** [comment]
From a preliminary look it seems that the dual axis panels are using two ModuleDeployableSolarPanel modules. The first, a tracking one with chargeRate 0. The second, a non-tracking one with chargeRate non-zero.

The author is creatively abusing the stock system. This mean that the first panel doesn't generate electricity, and the second one is threated as a fixed panel.

Unfortunately, it is technically impossible for me to detect this setup in-code.

Fortunately there is an easy fix for you: go in ChopShop\Electrics\SSP and open all the .cfg files in there.

In every file, look for these lines:

`// sunTracking = true`

`chargeRate = 0`

and replace with these ones:

`sunTracking = true`

`chargeRate = N`

where N is the charge rate of the solar panel. You can find this number a few lines below, in every one of these files. For example, in the Mk1_SSP, you will find this, 10 lines below: `chargeRate = 12`. In this case N is 12.

**Comment by lordcirth** [comment]
Wouldn't this make the solar panel charge twice as fast, since both the real panel and the dummy generate power?

**Comment by ShotgunNinja** [comment]
@lordcirth You are right, they will generate double EC  when the vessel is loaded, and the right EC in background. This is far from a proper solution.
