### ISSUE TITLE
Docked with stranded ship- EC, Food, & Oxygen added to all parts.

### ISSUE THREAD

**Issue by Fixitman64** [ShotgunNinja/Kerbalism#25]
I docked with a stranded ship (standard kerbal rescue mission) using vanilla grabber. Game paused for just a second to add supplies to derelict command pod (so the occupant won't die immediately I assume). But it added EC, food, & oxygen to all parts of rescue ship. So now my fuel tank, engine, RCS thrusters, etc, all hold charge, food, & oxygen. Has happened 3 times now.

**Comment by ShotgunNinja** [comment]
Thanks for reporting this. A fix will be in next version.

**Comment by ShotgunNinja** [comment]
Fixed in 1.0.0
