### ISSUE TITLE
shortAntenna is missing

### ISSUE THREAD

**Issue by CodeStage** [ShotgunNinja/Kerbalism#27]
I have installed RemoteTech. With 1.0.0 vessels with a shortAntenna can not be loaded any more. I assume this has been changed on purpose. Since I have both RemoteTech and Kerbalism parts on my station, I can't save the Kerbals. Any ideas?

**Comment by ShotgunNinja** [comment]
I'll readd it with proper RT config in next version. Meanwhile edit Kerbalism/Parts/ShortAntenna/shortAntenna.cfg and change the first line from
`PART:NEEDS[!RemoteTech,!AntennaRange,EnableSignal]` to `PART`

**Comment by CodeStage** [comment]
Cool, thanks!

**Comment by ShotgunNinja** [comment]
Fixed for next version: the short antenna will be unavailable if signal mechanic is disabled, but existing vessels will keep working.
