### ISSUE TITLE
Not sure where to post this question as i do not find this on the KSP forum.

### ISSUE THREAD

**Issue by Bit-Fiddler** [ShotgunNinja/Kerbalism#3]
Does this work along side TAC life support or conflict with it?  I assume the "Food" and "Oxygen" are the same resource TAC uses but your .dll running alongside his will cause problems?  not an issue really I can switch to your model if it does conflict, but I like the idea of "Food", "Oxygen", and "water". as it also gives us a better model for green houses and the ability to use the water for oxygen, and hydrogen etc.

or alternatively can we disable the life support function of this mod, and just use TAC instead?

And all of these questions basically duplicated for Remote Tech.  does your mod work along side, or conflict with remote tech?

**Comment by ShotgunNinja** [comment]
The forum is [there](http://forum.kerbalspaceprogram.com/index.php?/topic/137227-11-kerbalism/).

The mods you mention overlap in functionality with this one, so assume they are incompatible. Even if technically you should be able to run all together, it will just be a mess.

This mod share some names of resources with TAC, but that is just the result of how natural those names are.

The mod could also be used with RT, technically. But then some antenna will take the RT functionality and others this mod functionality. All based on the alphabetical order of the ModuleManager patches. And you'll need two antennas to satisfy both... as you can see its becoming a mess really fast.

Unfortunately, individual mechanics of this mod can't be disabled.

Feel free to come to the thread, and of course to have a look at the wiki. Cheers.
