### ISSUE TITLE
1.1.3 TimeWarp.SetRate change

### ISSUE THREAD

**Issue by de-odex** [ShotgunNinja/Kerbalism#31]
MissingMethodException: Method not found: 'TimeWarp.SetRate'.

Potential fix: either 
1. recompile
2. change TimeWarp.SetRate(TimeWarp.CurrentRateIndex - 1, true); to TimeWarp.SetRate(TimeWarp.CurrentRateIndex - 1, true, **true**);
find in src/Lib.cs lines 178-179. I am not sure what the 3rd parameter does, and have not found any information to what it does

fix 2 found here: http://forum.kerbalspaceprogram.com/index.php?/topic/139589-112-tac-life-support-v0121-release-12-may-2016/&page=4

**Comment by leomike** [comment]
I've taken a look and the 3rd parameter is labeled "PostMessage".
If you want a recompile for 1.1.3, you can check the forum. I've built one until we get an official update.
