### ISSUE TITLE
SCANsat update power usage

### ISSUE THREAD

**Issue by DMagic1** [ShotgunNinja/Kerbalism#33]
The latest SCANsat update switched from using custom resource handling to using the stock ModuleResource: https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/SCAN_PartModules/SCANsat.cs#L166-L182

The loaded ModuleResources are stored in a public list: https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/SCAN_PartModules/SCANsat.cs#L33

This obviously breaks the old method for handling background scanner EC usage.

**Comment by ShotgunNinja** [comment]
Thanks, fixed in next version.
