### ISSUE TITLE
DMagic/Universal Storage Modules

### ISSUE THREAD

**Issue by cvelde** [ShotgunNinja/Kerbalism#36]
I noticed that the goo and science lab "wedges" for Universal Storage from the dmagic orbital science mod are in the original tech nodes. I assume this is not intentional (or hasn't been seen/fixed yet)?

Small fix for ScienceTweaks.cfg:

```
@PART[dmUSGoo]:FOR[Kerbalism]:NEEDS[DMagic]
{
  @TechRequired = basicScience
}
@PART[dmUSMat]:FOR[Kerbalism]:NEEDS[DMagic]
{
  @TechRequired = spaceExploration
}
```

**Comment by ShotgunNinja** [comment]
Thanks, I've committed it. Will be included in next version.
