### ISSUE TITLE
Minor copy-editing in Message.cs

### ISSUE THREAD

**Issue by Squelch7** [ShotgunNinja/Kerbalism#4]
Hi:

I did some minor copy editing on the messages in the Post methods. I've attached a text file
[message.cs excerpt.txt](https://github.com/ShotgunNinja/Kerbalism/files/232960/message.cs.excerpt.txt)
. Search for "FIXED" to see the comments that explain the changes. (Sorry, I would do a diff if I had the capacity on this computer.)

Really enjoying the mod; thanks for your super-quick replies on the forum. Looking forward to the future.

**Comment by ShotgunNinja** [comment]
Thanks, I'm going to integrate this in next version.
