### ISSUE TITLE
ETT Techtree High Gain Antenna Tech can't be researched

### ISSUE THREAD

**Issue by Chase22** [ShotgunNinja/Kerbalism#45]
I've discovered a strange Bug with Kerbalism and the Engineering Tech Tree. The two Nodes "High Gain Antennas" and "Advanced Long Range Antennas" don't work properly:

High Gain Antennas: The Technode can got the Purchase Button from the Start of the Game (See Screenshot). If you research the Node and purchase the Items, it removes the Funds, but you dont get the parts. All the Parts are missing in the VAB, even in Saves where they were available before the installation of Kerbalism. If i had them already on a vessel, its fine, but saved Vessels wont work.

Advanced Long Range Antennas: This Node is unlocked from the Start and can be researched.

When i start a game with the Stock tree, everything workes fine.

KSP 1.2.2
Kerbalism 1.1.5

![screenshot0](https://cloud.githubusercontent.com/assets/4669075/21289832/09311ffc-c4a7-11e6-8da5-1a0d57e6dfca.png)

**Comment by ShotgunNinja** [comment]
There is some similar reports on the ETT forum thread located [here](http://forum.kerbalspaceprogram.com/index.php?/topic/112627-12x-ett-engineering-tech-tree-dec-11th-2016/&page=1), in last couple of pages. The reports doesn't seem to indicate the issue is related to Kerbalism, however.

**Comment by Chase22** [comment]
Okay, seems like a false coherence. I updated from 1.2.1 to 1.2.2 and installed Kerbalism.

The Quickfix from ETT worked. So this issue can be closed.
