### ISSUE TITLE
EC High script trigger too low

### ISSUE THREAD

**Issue by NetzwergX** [ShotgunNinja/Kerbalism#48]
The EC high trigger is set to 15%, which does not make much sense. I suggest setting it to 85% or another value that is actually "high".

Currently I see no good use for the trigger. Its the same value as the EC Low trigger.

I have a vessel that has a fuel cell. Unfortunately, the fuel cell produces more fuel then the vesel consumes, but without a running fuel cell, the vessels EC depletes. I though fine, just add some trigger. I set the fuel cell to enable when EC drops below 15%, and set the fuel cell to enable on EC high. Since both are at 15%, the vessel is now constantly at 15% EC and constantly switches the Fuel Cell on and off.

That behavior is obviuosly nonsense. It would make much more sense to activate the fuel cell at 15%, let it run until 85%, then disable it, rinse and repeat. this would also allow someone to do some EC intense things that greatly dminish EC reserves, and then let EC fill up again, without having to enable/disable the parts manually. Not to mention that is constantly screws with time-warping if the script enables/disables constantly.

I'm not sure if its intended that EC High is at 15%, but I don't see any usage case for that. (85% would be much more reasonable).

The script system is really great btw ;)

**Comment by ShotgunNinja** [comment]
I've set it to 20% for power_low, and 80% for power_high.

**Comment by NetzwergX** [comment]
Great, that should de very well. Thanks for getting on it so quickly.
