### ISSUE TITLE
Monitor does not show remaining oxygen when scrubber is running

### ISSUE THREAD

**Issue by eglia** [ShotgunNinja/Kerbalism#5]
As the title says. Tested in sandbox with stock "Kerbal X" rocket. When the scrubber is activated, the monitor only shows remaining food:
![screenshot9](https://cloud.githubusercontent.com/assets/17555261/14761974/29fef306-096f-11e6-98bc-74e7a2063392.png)
When the scrubber is deactivated, food and oxygen is displayed:
![screenshot10](https://cloud.githubusercontent.com/assets/17555261/14761977/30472634-096f-11e6-9989-6eed899c4154.png)

KSP 1.1.0 x64
Kerbalism 0.9.9.3

**Comment by ShotgunNinja** [comment]
This finally should be fixed now. In next release.
