### ISSUE TITLE
`Configure` module depends on all `ProcessController` modules it references to be defined before it

### ISSUE THREAD

**Issue by YaarPodshipnik** [ShotgunNinja/Kerbalism#57]
If a `ProcessController` is referenced by a `Configure` module, but is defined textually after the `Configure` module, then an option to choose a given setup will be present, but there will be no values displayed for a given process.

Repro:
1. in Default.cfg move `ProcessController` for SOE after `Configure` of chemical plant
2. try to use SOE in game, see that the description is shown but there are no values for the process.

This is making writing patches to add processes harder, as MM seems to add new modules at the end of the list by default. 58288e3 works around that by using `MODULE,0`, but it would be easier for contributors if this wasn't necessary.

**Comment by ShotgunNinja** [comment]
Fixed, thanks as always.
