### ISSUE TITLE
Kerbals Not Eating

### ISSUE THREAD

**Issue by AlexwareRBLX** [ShotgunNinja/Kerbalism#6]
Is this just a problem with my client? I go take food on my ship, I even looked at it while I was in time lapse, none of the food was depleting, but my colonists were starving, they had PLENTY of food in each module. I tried getting out, and back in, right clicking to see if there was a "Feed kerbals" button, is there anything I'm missing addon wise? (I have this + module manager)
Should I reinstall?

**Comment by ShotgunNinja** [comment]
Hi, are you using PlanetaryBaseSystems?

**Comment by kyrcant** [comment]
no.

On Sun, Apr 24, 2016 at 3:32 PM, ShotgunNinja <notifications@github.com>
wrote:

> Hi, are you using PlanetaryBaseSystems?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShotgunNinja/Kerbalism/issues/6#issuecomment-214025920>
>



-- 

Be well, do good work, keep in touch.

**Comment by ShotgunNinja** [comment]
Is possible that it was a savegame created before adding this game?

**Comment by ShotgunNinja** [comment]
Nevermind, I was finally able to replicate the issue. A fix is on the way.

**Comment by ShotgunNinja** [comment]
fixed in 0.9.9.4
