### ISSUE TITLE
Monitor: forget selected vessel if it become invalid after selection

### ISSUE THREAD

**Issue by dramsey-rcs** [ShotgunNinja/Kerbalism#60]
Manually setting a vessel to Debris causes the Kerbalism UI to no longer list any vessels.   Setting the vessel back to any other type allows the UI to function properly again.  Issue does not seem to affect debris created from decoupling or crashes.

![debris-1](https://cloud.githubusercontent.com/assets/19180447/21835469/3c6a6616-d78b-11e6-8548-b1a3519f625a.png)
![rename-1](https://cloud.githubusercontent.com/assets/19180447/21835473/44ba1398-d78b-11e6-8bf4-2ff2c25ccfc9.png)

**Comment by ShotgunNinja** [comment]
I have this concept of 'invalid vessels', that are completely ignored by the simulation engine: that is, they do not exist as far as this mod is concerned.

The invalid vessels are:
- debris
- flags
- asteroids
- unknown objects
- dead EVA kerbals
- resque mission vessels

However there is a bug here, in the Monitor. It should have 'de-selected' the vessel when it was flagged as debris (thus showing the 'no vessels' string).

Anyway, thanks for the report.

**Comment by dramsey-rcs** [comment]
No problem!

**Comment by ShotgunNinja** [comment]
fixed [here](https://github.com/ShotgunNinja/Kerbalism/commit/9e92ff1ba7a67a94d80997cf443b50199af97f72)
