### ISSUE TITLE
Habitat: dump WasteAtmosphere during venting

### ISSUE THREAD

**Issue by dramsey-rcs** [ShotgunNinja/Kerbalism#63]
It would make sense if venting a habitat would dump WasteAtmosphere when it dumps the Atmosphere.

**Comment by ShotgunNinja** [comment]
I agree.

**Comment by ShotgunNinja** [comment]
Implemented [here](https://github.com/ShotgunNinja/Kerbalism/commit/3ad41849e24ca3f157c2b0282a6bbb333eafb9ed).
