### ISSUE TITLE
Antennas don't break in atmospheric flight

### ISSUE THREAD

**Issue by CaesarVincens** [ShotgunNinja/Kerbalism#64]
The Kerbalism Antenna module does not have a max pressure/Q value which results in antennas being indestructible to aero forces unlike stock, removing some of the balance between fixed and deployable antennas

**Comment by ShotgunNinja** [comment]
You are right. That is a consequence of the use of ModuleAnimation*, instead of ModuleDeployable*. Apparently, the atmosphere breaking is implemented by the latter.
