### ISSUE TITLE
Automation device for ScanSAT throw exception

### ISSUE THREAD

**Issue by dramsey-rcs** [ShotgunNinja/Kerbalism#65]
When the DMagic Multi-Spectral Imaging Platform sensor is installed on a craft, the Auto menu does not display, and the following line shows up in the log:

[EXC 21:22:09.166] ArgumentException: An element with the same key already exists in the dictionary.
	System.Collections.Generic.Dictionary`2[System.UInt32,KERBALISM.Device].Add (UInt32 key, KERBALISM.Device value)
	KERBALISM.Computer.boot (.Vessel v)
	KERBALISM.DevManager.devman (KERBALISM.Panel p, .Vessel v)
	KERBALISM.Monitor.update ()
	KERBALISM.Launcher.update ()
	KERBALISM.UI.update (Boolean show_window)
	KERBALISM.Kerbalism.Update ()

Can provide logs if needed.

**Comment by ShotgunNinja** [comment]
fixed [here](https://github.com/ShotgunNinja/Kerbalism/commit/4e64421443032dc6965957ea98d98e7c9b0205e6)
