### ISSUE TITLE
Remote Tech friendly?

### ISSUE THREAD

**Issue by kyrcant** [ShotgunNinja/Kerbalism#7]
I love Kerbalism - but I've always played with remote-tech and would like to continue in that.  Is there a way to disable just the signals part of the mod?

Also, Kerbalism doesn't play with Near Future Solar panels.  Keeps saying it has run out of charge, because it treats the panels as though they can't re-direct towards the sun.  I'm not a coder, so I don't know what the Near Future Solar CFG file does, but it doesn't appear to work.

**Comment by ShotgunNinja** [comment]
You are right, the curved panels aren't working , I'm working on a fix. Is the problem only present in curved ones, can you confirm this?

**Comment by ShotgunNinja** [comment]
About disabling part of the mod: this is on my todo list, but low priority.

**Comment by Lomare** [comment]
Unfortunately any mod that adds Antenna will not work either.  I presume due the Kerbalism Antenna fields not being populated/defined.

**Comment by ShotgunNinja** [comment]
curved panels fixed in next version

for the other antennas not working: the new version use a 'default antenna' with sane defaults, also in next versions
