### ISSUE TITLE
Life support simulation stops for kerbals returning from eva on the surface of a planet.

### ISSUE THREAD

**Issue by klugeh01** [ShotgunNinja/Kerbalism#75]
When kerbals return from the surface of a planet, they no longer consume any life support supplies (food, water, oxygen). Restarting the game fixes, but this occurs any time a kerbal has set foot on the surface of a planet (or moon). The simulation only stops for that kerbal, and they have to have actually set foot on the surface. If they stay on a ladder this doesn't happen. Possible interaction with deepfreeze or KIS/KAS.

**Comment by klugeh01** [comment]
Turns out I missed a patch for DeepFreeze.... oops

**Comment by klugeh01** [comment]
Issue happens after placing a flag on EVA

**Comment by ShotgunNinja** [comment]
Thanks for the feedback. I was finally able to reproduce this.

**Comment by ShotgunNinja** [comment]
References:
- additional reproduction steps + savegame test case: [here](http://forum.kerbalspaceprogram.com/index.php?/topic/137227-122-kerbalism-v120/&page=153#comment-2974510)

**Comment by ShotgunNinja** [comment]
Finally fixed!
