### ISSUE TITLE
Disabling SpaceWeather feature in settings.cfg cause exceptions

### ISSUE THREAD

**Issue by gotmachine** [ShotgunNinja/Kerbalism#78]
With "SpaceWeather=false", i'm getting exception spam while in flight :

> [EXC 17:14:48.731] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List`1[KERBALISM.Kerbalism+storm_data].get_Item (Int32 index)
	KERBALISM.Kerbalism.FixedUpdate ()

**Comment by ShotgunNinja** [comment]
Thanks, this has been fixed [here](https://github.com/ShotgunNinja/Kerbalism/commit/153e6291d1a28b560f19f7e2d3fd286ee6a90c42).
