### ISSUE TITLE
Stop cancelling time warp for certain warning messages

### ISSUE THREAD

**Issue by DaveTSG** [ShotgunNinja/Kerbalism#89]
Aloha!

I often find my time warps are cancelled due to Kerbalism sending warning messages that don't really need to be handled, e.g.: "Radiator failed on Eve Orbiter, but we were able to fix it remotely."

This sort of error message isn't really important. There isn't anything that can be done other than noting that the failure happened. 

Could you please make it so that this type of message doesn't cancel time warping?

Conversely, errors such as "Radiator on Eve Orbiter failed, but an engineer can fix still fix it" obviously should stop time warp.

Thank you. :)

**Comment by ShotgunNinja** [comment]
Implemented [here](https://github.com/ShotgunNinja/Kerbalism/commit/814e3c2a4f80d17b25e3e0dbcdd736a8c2d898cb).

**Comment by DaveTSG** [comment]
Thanks! 😊
