### ISSUE TITLE
Non-regenerative EVA scrubber

### ISSUE THREAD

**Issue by ShotgunNinja** [ShotgunNinja/Kerbalism#91]
Using a 'self-consuming process', it is possible to implement a non-regenerative scrubber, the kinds used before or in alternative to dual-bed vacuum-exposing ones.

While it could be interesting as an early-game choice for manned pods, it seem ideal to use these for EVA kerbals. This will allow to decrease EC consumption for EVA kerbals (as the non-regen scrubber will not require EC).

**Comment by PiezPiedPy** [comment]
Sounds like a good idea, as currently the EC does not last that long when on EVA.

**Comment by ShotgunNinja** [comment]
Implemented [here](https://github.com/ShotgunNinja/Kerbalism/commit/9689ac02d0699d67cfef8375c20b8bed016659a3).
