### ISSUE TITLE
Relay

### ISSUE THREAD

**Issue by Hury999** [ShotgunNinja/Kerbalism#94]
I don't get it. I can't relay signal. Maybe I do something wrong but is there tutorial for that?

**Comment by ShotgunNinja** [comment]
There is a [wiki ](https://github.com/ShotgunNinja/Kerbalism/wiki/Signal) here. Only low-gain antennas (the whips) can communicate with other vessels. The high-gain antennas (the dishes) instead can only communicate with the home body.

So, to create a 'relay satellite', you just need to add both a low-gain and an high-gain antenna. Then right-click on the low-gain and set 'relay' to true. That satellite will then relay data from/to the home body and other vessels. Make sure both antennas are deployed, else they will not work.

Feel free to ask a more specific question if the above doesn't help you.
